CREATE TABLE project
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_name        VARCHAR(255),
    project_description VARCHAR(255),
    project_status      BOOLEAN,
    CONSTRAINT pk_project PRIMARY KEY (id)
);