CREATE TABLE project
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_name        VARCHAR(255),
    project_description VARCHAR(255),
    project_end_date    TIMESTAMP WITHOUT TIME ZONE,
    project_status      VARCHAR(255),
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    role       VARCHAR(255),
    email      VARCHAR(255),
    project_id BIGINT,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE task
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    last_modified TIMESTAMP WITHOUT TIME ZONE,
    project_id    BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);